name: Build

on:
  push:
    branches-ignore:
      - master

jobs:

  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build
      run: xcodebuild build -scheme CryptoCurrency -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
      
    - name: Run Tests
      run: xcodebuild test -scheme CryptoCurrency -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'