name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
  
jobs:

  build:
  
    runs-on: macOS-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Clean
      run: xcodebuild clean -scheme CryptoCurrency -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
      
    - name: Build
      run: xcodebuild build -scheme CryptoCurrency -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
      
    - name: Run Tests
      run: xcodebuild test -scheme CryptoCurrency -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'