name: iOS Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: macos-14
    strategy:
      matrix:
        include:
          - xcode: "15.1"
            ios: "17.2"
          - xcode: "15.1"
            ios: "16.0"
    name: Test iOS (${{ matrix.ios }})
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_$.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: xcodebuild test -scheme BudgetOnTheGo -project BudgetOnTheGo.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15,OS=$' | xcpretty && exit ${PIPESTATUS[0]}